FROM dustynv/pytorch:2.6-r36.4.0-cu128

ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /opt

# System deps that commonly matter for robotics + video + OpenCV
RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    ffmpeg \
    libgl1 \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender1 \
 && rm -rf /var/lib/apt/lists/*

# Upgrade pip tooling
RUN python3 -m pip install --upgrade pip setuptools wheel

# Get fork lerobot repo
RUN git clone --depth 1 https://github.com/MyLovelyAxe/lerobot.git
WORKDIR /opt/lerobot

# Install torchvision compatible with torch 2.6 (and matching lerobot requirement range)
RUN pip install "torchvision>=0.21.0,<0.22.0" \
    -i https://pypi.org/simple \
    --extra-index-url https://pypi.ngc.nvidia.com \
    --extra-index-url http://jetson.webredirect.org/jp6/cu126

# Install lerobot + smolvla deps
RUN pip install -e ".[smolvla]" --no-build-isolation \
    -i https://pypi.org/simple \
    --extra-index-url https://pypi.ngc.nvidia.com \
    --extra-index-url http://jetson.webredirect.org/jp6/cu126

# quickly test the versions
RUN python3 -c "import torch, torchvision; \
print('torch:', torch.__version__); \
print('torchvision:', torchvision.__version__); \
print('cuda available:', torch.cuda.is_available())"
